name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  
  build:
    runs-on: ubuntu-latest
    
    steps:

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Pull docker image
    run: sudo docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Run docker container
    run: sudo docker run -d -p 8080:8080 --name cicd-pipeline-container $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
